### ISSUE TITLE
Allow option with empty value

### ISSUE THREAD

**Issue by javve** [ember-a11y/ember-select-light#25]
Thanks a lot for a nice lib. I'm currently in the process of switching from x-select to ember-select-light and I found something I would consider a bug.

It's not possible to have an option with a value that is just an empty string. 

```
<SelectLight @value={{value}} @change={{action "myAction"}} @options={{selectOptions}} />
```

```
get selectOptions() {
  return [{
    label: 'Nothing',
    value: ''
  },{
    label: 'Option 1',
    value: '1'
  }]
}
```

At the moment this will result in this:
![image](https://user-images.githubusercontent.com/123192/97988459-4f479000-1ddd-11eb-8a03-2aca304ec88c.png)
![image](https://user-images.githubusercontent.com/123192/97988491-5b335200-1ddd-11eb-89d8-627369c080eb.png)

**Comment by javve** [comment]
I created a PR if you're interested in allowing empty string as value :v: Check out: https://github.com/ember-a11y/ember-select-light/pull/26

**Comment by hergaiety** [comment]
@javve hey! I've updated my notification settings for this repository so that I'll notice these more quickly. Thanks for your patience on this.

Great issue logging and I highly appreciate the PR. It's been merged and a new patch release has been published to npm https://github.com/ember-a11y/ember-select-light/releases/tag/v2.0.4

**Comment by javve** [comment]
Awesome @hergaiety! No worries, I've been using my fork until now with no issues :v:
Thanks for the merge.
